### ISSUE TITLE
建议恢复css3相关的-webkit-前缀变量

### ISSUE THREAD

**Issue by hands3dlabs** [sdc-alibaba/SUI-Mobile#157]
经测试发现，一些基于ios8.4的safari浏览器仍然需要-webkit-前缀支持才能执行一些动画，例如 scaleY

**Comment by Mickey-** [comment]
能举例给我们看下哪些地方缺少了吗？

我们用postcss 进行autoprefix的，并且兼容safari是从safari6开始的，所以开发时并没太关心具体prefix了。

**Comment by hands3dlabs** [comment]
比如mixins.less里面，找一些`scaleY`

``` css
@media only screen and (-webkit-min-device-pixel-ratio: 2) {
    transform: scaleY(0.5);
}
```

还有比如forum.less

``` css
input[type="checkbox"] {
        display: none;
        &:checked {
            &+ .checkbox {
                background: @color-success;
                &:before {
                    transform: scale(0);
                }
                &:after {
                    transform: translateX(1.1rem);
                }
            }
        }
    }
```

另外一些 `animation` 如果不带前缀在iphone5, iso8.2的safari中就无效了
