### ISSUE TITLE
$.router.load("#pageid") 禁用跳转动画

### ISSUE THREAD

**Issue by 9kl** [sdc-alibaba/SUI-Mobile#311]
您好，
请内连页面哪多个page切换，使用js $.router.load("#pageid")  如何禁用跳转动画呢？

**Comment by Mickey-** [comment]
可以给特定pageid的page元素附加业务级css禁用transition动画。

另外一部分禁用转场效果的场景，可以用非路由体系实现（external）

**Comment by ufologist** [comment]
我是这样尝试解决的:

**通过强制让某些页是0时长动画来实现底部工具栏路由"跳转"页面时不会伴随有动画效果**

假设我有三个页面
- index.html
  
  ``` html
  <div class="page-group page-group-index">
  ```
- customize.html
  
  ``` html
  <div class="page-group page-group-customize">
  ```
- profile.html
  
  ``` html
  <div class="page-group page-group-profile">
  ```

然后设置如下的样式

``` css
/* 通过强制让某些页是0时长动画来实现底部工具栏路由"跳转"页面时不会伴随有动画效果 */
.page-group-index,
.page-group-customize,
.page-group-profile /*.page-group-profile.page-from-right-to-center*/ {
                    /* 可以根据情况只禁用部分页面切换方向的动画 */ 
    -webkit-animation-duration: 0s;
            animation-duration: 0s;
}
```

**但是在手机端或者浏览器上测试时发现, 快速切换过程中会出现"跳转"错乱的问题, 方案仅供参考..**
要避免"跳转"错乱的问题, 可以尝试禁用路由缓存

完整代码可以参考 [mobile-spa-boilerplate](https://github.com/appbone/mobile-spa-boilerplate)
